spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: books
        uri: lb://books
        predicates:
        - Path=/books
        - Method=GET

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
